# Generated by Django 5.0.2 on 2024-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyordermodel',
            name='product',
        ),
        migrations.AddField(
            model_name='historyordermodel',
            name='product',
            field=models.ManyToManyField(to='main.productmodel'),
        ),
    ]
