# Generated by Django 5.0.2 on 2024-03-24 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_historyordermodel_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyordermodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.usermodel'),
        ),
    ]
